name:                stearnswharf 
version:             0.9.1
github:              "githubuser/demo3"
license:             BSD3
author:              "Rolf C Stadheim"
maintainer:          "rolf.c.stadheim@gmail.com"
copyright:           "2019 Rolf C Stadheim"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/demo3#readme>

dependencies:
- base >= 4.7 && < 5
- cmdargs 
- containers
- hmatrix
- HUnit
- mtl
- optparse-applicative
- postgresql-simple
- utf8-string
- xml

library:
  source-dirs: src

executables:
  stearnswharf-0.9.1:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wcompat
    - -Widentities
    - -Wpartial-fields
    - -Wredundant-constraints

    dependencies:
    - stearnswharf 

tests:
  stearnswharf-test:
    main:                testStearnsWharf.hs
    source-dirs:         t
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stearnswharf
